### ISSUE TITLE
Update kupo operator k8s resources

### ISSUE THREAD

**Issue by paulobressan** [demeter-run/ext-cardano-kupo#77]
Repositories

- [x] Kupo Ext

```
resources:
   limits:
      cpu: 300m
      memory: 1Gi
   requests:
      cpu: 100m
      memory: 756Mi
```
